Change format mp3
Yuta123456/geekuten_backend pull request #2
Opened 2021-06-15 08:48 UTC by sanma-mod

受け取った音声ファイルをmp3に変更し、exportする関数を追加

2021-06-15 11:57 UTC, Yuta123456 reviewed
恐らく、引数はファイルへのパスですよね。そうすると変数名が適切じゃない気がします。同様にdocstringも編集してください。

2021-06-15 11:59 UTC, Yuta123456 requested changes
~~また、ファイル名が`fuga.mp3`で毎回保存されるのしんどいので、引数で値を取りましょう。~~
~~ただテストするときにはめんどくさいので、デフォルト値を設定しておきましょう。~~
```
def to_mp3(audio_file, new_path_name = "fuga.mp3"):
```
~~のように記述すると引数が省略された際のデフォルト値を設定できます。~~

ごめんなさい。デフォルト値が省略されたらファイル名は変更しないようにしましょう。例えば、`sample.wav`が引数に来たら、`sample.mp3`で保存するようにしますか。

2021-06-15 12:03 UTC, Yuta123456 requested changes
関数の設計も少し考えましょう。自分がこの関数を使う時にどうであったら使いやすいか。
今回で言えば、保存されているファイルパスを文字列で返してあげると使いやすいだろうとか？
この関数名だと、例えば直感的に僕が使うなら、
```
audio_mp3 = to_mp3("sample.wav")
```
のように使ってしまいそう。

2021-06-15 12:04 UTC, Yuta123456 requested changes
あとこれ、ちゃんと動きますか？
`audio_format = audio_file[audio_file.find(".")+1]`
じゃなく、
`audio_format = audio_file[audio_file.find(".")+1:]`
じゃない？気のせい？

2021-06-16 04:59 UTC, Yuta123456 requested changes
なんか二つファイルの変更ないですか？

2021-06-16 07:34 UTC, sanma-mod commented
ファイルが2つあるっていうのは、to_mp3.pyとexport_mp3.pyの2つあるって意味であってますか？その場合であればto_mp3.pyの方は削除します

2021-06-17 08:11 UTC, merged